// Static registry of major science facilities shown on the globe.
// feedUrl: RSS/Atom polled by the science-news job; null = status only.
import IMAGES from "./facility-images.json";

export interface Facility {
  id: string;
  name: string;
  short: string; // label on the map tag
  kind: "gravitational-wave" | "particle" | "observatory" | "radio" | "fusion" | "detector" | "space";
  lat: number;
  lon: number;
  location: string;
  url: string;
  feedUrl: string | null;
  blurb: string;
  image?: string | null; // local cover image under /facilities/, when downloaded
}

const IMAGE_MAP = IMAGES as Record<string, string>;

export const FACILITIES: Facility[] = [
  {
    id: "ligo-hanford",
    name: "LIGO Hanford",
    short: "LIGO-H",
    kind: "gravitational-wave",
    lat: 46.4551, lon: -119.4077,
    location: "Hanford, WA, USA",
    url: "https://www.ligo.caltech.edu/WA",
    feedUrl: null, // ligo.org is behind Cloudflare — feeds 403 to bots
    blurb: "4km laser interferometer; co-discovered gravitational waves in 2015.",
  },
  {
    id: "ligo-livingston",
    name: "LIGO Livingston",
    short: "LIGO-L",
    kind: "gravitational-wave",
    lat: 30.5629, lon: -90.7742,
    location: "Livingston, LA, USA",
    url: "https://www.ligo.caltech.edu/LA",
    feedUrl: null,
    blurb: "Twin of Hanford — coincident detection is what confirms a real wave.",
  },
  {
    id: "virgo",
    name: "Virgo Interferometer",
    short: "Virgo",
    kind: "gravitational-wave",
    lat: 43.6314, lon: 10.5045,
    location: "Cascina, Italy",
    url: "https://www.virgo-gw.eu/",
    feedUrl: null,
    blurb: "3km European interferometer; third node of the GW detector network.",
  },
  {
    id: "kagra",
    name: "KAGRA",
    short: "KAGRA",
    kind: "gravitational-wave",
    lat: 36.412, lon: 137.306,
    location: "Kamioka, Japan",
    url: "https://gwcenter.icrr.u-tokyo.ac.jp/en/",
    feedUrl: null,
    blurb: "Underground cryogenic interferometer — the fourth GW detector.",
  },
  {
    id: "cern",
    name: "CERN (LHC)",
    short: "CERN",
    kind: "particle",
    lat: 46.233, lon: 6.0557,
    location: "Geneva, Switzerland",
    url: "https://home.cern/",
    feedUrl: "https://home.cern/news/rss/feed",
    blurb: "27km Large Hadron Collider — Higgs boson, and the biggest machine ever built.",
  },
  {
    id: "fermilab",
    name: "Fermilab",
    short: "Fermilab",
    kind: "particle",
    lat: 41.8319, lon: -88.2572,
    location: "Batavia, IL, USA",
    url: "https://www.fnal.gov/",
    feedUrl: "https://news.fnal.gov/feed/",
    blurb: "US neutrino & muon physics hub; hosts DUNE's near detector and Muon g-2.",
  },
  {
    id: "slac",
    name: "SLAC National Accelerator Lab",
    short: "SLAC",
    kind: "particle",
    lat: 37.4148, lon: -122.2047,
    location: "Menlo Park, CA, USA",
    url: "https://slac.stanford.edu/",
    feedUrl: null, // no public RSS found
    blurb: "3km linear accelerator + LCLS X-ray free-electron laser.",
  },
  {
    id: "brookhaven",
    name: "Brookhaven (RHIC)",
    short: "RHIC",
    kind: "particle",
    lat: 40.8832, lon: -72.8707,
    location: "Upton, NY, USA",
    url: "https://www.bnl.gov/",
    feedUrl: null, // newsroom RSS endpoint is dead
    blurb: "Relativistic Heavy Ion Collider — quark-gluon plasma; future EIC site.",
  },
  {
    id: "rubin",
    name: "Vera C. Rubin Observatory",
    short: "Rubin",
    kind: "observatory",
    lat: -30.2446, lon: -70.7494,
    location: "Cerro Pachón, Chile",
    url: "https://rubinobservatory.org/",
    feedUrl: null, // site blocks feed readers (403)
    blurb: "8.4m survey telescope imaging the whole southern sky every few nights (LSST).",
  },
  {
    id: "paranal",
    name: "ESO Paranal (VLT)",
    short: "VLT",
    kind: "observatory",
    lat: -24.6272, lon: -70.4042,
    location: "Atacama, Chile",
    url: "https://www.eso.org/public/teles-instr/paranal-observatory/vlt/",
    feedUrl: "https://www.eso.org/public/news/feed/",
    blurb: "Four 8.2m Unit Telescopes — the most productive optical observatory on Earth.",
  },
  {
    id: "alma",
    name: "ALMA",
    short: "ALMA",
    kind: "radio",
    lat: -23.029, lon: -67.755,
    location: "Chajnantor, Chile",
    url: "https://almaobservatory.org/",
    feedUrl: "https://almaobservatory.org/en/feed/",
    blurb: "66-dish millimeter array at 5,000m — images planet-forming disks & black holes.",
  },
  {
    id: "keck",
    name: "W. M. Keck Observatory",
    short: "Keck",
    kind: "observatory",
    lat: 19.8263, lon: -155.473,
    location: "Mauna Kea, HI, USA",
    url: "https://keckobservatory.org/",
    feedUrl: "https://keckobservatory.org/feed/",
    blurb: "Twin 10m segmented mirrors on the best Northern-hemisphere site.",
  },
  {
    id: "subaru",
    name: "Subaru Telescope",
    short: "Subaru",
    kind: "observatory",
    lat: 19.8255, lon: -155.4761,
    location: "Mauna Kea, HI, USA",
    url: "https://subarutelescope.org/",
    feedUrl: null, // press page has no RSS
    blurb: "8.2m Japanese flagship with Hyper Suprime-Cam wide-field imaging.",
  },
  {
    id: "vla",
    name: "Very Large Array",
    short: "VLA",
    kind: "radio",
    lat: 34.0784, lon: -107.6184,
    location: "Socorro, NM, USA",
    url: "https://public.nrao.edu/telescopes/vla/",
    feedUrl: "https://public.nrao.edu/feed/",
    blurb: "27 dishes in a Y — the workhorse of radio astronomy since 1980.",
  },
  {
    id: "greenbank",
    name: "Green Bank Observatory",
    short: "GBT",
    kind: "radio",
    lat: 38.4331, lon: -79.8397,
    location: "Green Bank, WV, USA",
    url: "https://greenbankobservatory.org/",
    feedUrl: "https://greenbankobservatory.org/feed/",
    blurb: "100m fully-steerable dish inside the National Radio Quiet Zone.",
  },
  {
    id: "arecibo",
    name: "Arecibo Observatory",
    short: "Arecibo",
    kind: "radio",
    lat: 18.3442, lon: -66.7528,
    location: "Arecibo, Puerto Rico",
    url: "https://www.naic.edu/",
    feedUrl: null,
    blurb: "Iconic 305m dish — collapsed Dec 2020. Site now a STEM education center.",
  },
  {
    id: "fast",
    name: "FAST (Five-hundred-meter Aperture)",
    short: "FAST",
    kind: "radio",
    lat: 25.6529, lon: 106.8566,
    location: "Guizhou, China",
    url: "https://fast.bao.ac.cn/",
    feedUrl: null,
    blurb: "World's largest filled-aperture dish; leads pulsar discovery counts.",
  },
  {
    id: "parkes",
    name: "Parkes (Murriyang)",
    short: "Parkes",
    kind: "radio",
    lat: -32.9984, lon: 148.2636,
    location: "NSW, Australia",
    url: "https://www.csiro.au/en/about/facilities-collections/atnf/parkes-murriyang",
    feedUrl: null,
    blurb: "64m dish that relayed Apollo 11 TV; still finds half of all known pulsars.",
  },
  {
    id: "jodrell",
    name: "Jodrell Bank (Lovell)",
    short: "Jodrell",
    kind: "radio",
    lat: 53.2362, lon: -2.3071,
    location: "Cheshire, UK",
    url: "https://www.jodrellbank.net/",
    feedUrl: "https://www.jodrellbank.net/feed/",
    blurb: "76m Lovell telescope, UNESCO site, HQ of the SKA-Low pathfinder era.",
  },
  {
    id: "effelsberg",
    name: "Effelsberg 100-m",
    short: "Effelsberg",
    kind: "radio",
    lat: 50.5247, lon: 6.8828,
    location: "Bonn, Germany",
    url: "https://www.mpifr-bonn.mpg.de/en/effelsberg",
    feedUrl: null,
    blurb: "One of the two largest fully-steerable dishes; VLBI workhorse.",
  },
  {
    id: "icecube",
    name: "IceCube Neutrino Observatory",
    short: "IceCube",
    kind: "detector",
    lat: -89.99, lon: -63.45,
    location: "South Pole, Antarctica",
    url: "https://icecube.wisc.edu/",
    feedUrl: "https://icecube.wisc.edu/news/feed/",
    blurb: "A cubic kilometer of Antarctic ice instrumented to catch neutrinos.",
  },
  {
    id: "superk",
    name: "Super-Kamiokande",
    short: "Super-K",
    kind: "detector",
    lat: 36.4267, lon: 137.3104,
    location: "Kamioka, Japan",
    url: "https://www-sk.icrr.u-tokyo.ac.jp/en/",
    feedUrl: null,
    blurb: "50k-ton water Cherenkov detector — Nobel-winning neutrino oscillations.",
  },
  {
    id: "snolab",
    name: "SNOLAB",
    short: "SNOLAB",
    kind: "detector",
    lat: 46.4747, lon: -81.1868,
    location: "Sudbury, Canada",
    url: "https://www.snolab.ca/",
    feedUrl: "https://www.snolab.ca/feed/",
    blurb: "2km underground in a nickel mine — dark matter & neutrino experiments.",
  },
  {
    id: "lngs",
    name: "Gran Sasso (LNGS)",
    short: "LNGS",
    kind: "detector",
    lat: 42.454, lon: 13.5755,
    location: "L'Aquila, Italy",
    url: "https://www.lngs.infn.it/en",
    feedUrl: null,
    blurb: "Largest underground lab; OPERA, Borexino and dark-matter hunts.",
  },
  {
    id: "iter",
    name: "ITER",
    short: "ITER",
    kind: "fusion",
    lat: 43.7089, lon: 5.7819,
    location: "Cadarache, France",
    url: "https://www.iter.org/",
    feedUrl: "https://www.iter.org/rss.xml",
    blurb: "35-nation tokamak aiming for Q=10 fusion gain — first plasma late 2020s.",
  },
  {
    id: "nif",
    name: "National Ignition Facility",
    short: "NIF",
    kind: "fusion",
    lat: 37.6887, lon: -121.7036,
    location: "Livermore, CA, USA",
    url: "https://www.llnl.gov/nif-computing",
    feedUrl: "https://www.llnl.gov/rss.xml",
    blurb: "192-beam laser that achieved fusion ignition (net energy gain) in 2022.",
  },
  {
    id: "wendelstein",
    name: "Wendelstein 7-X",
    short: "W7-X",
    kind: "fusion",
    lat: 53.5497, lon: 13.4228,
    location: "Greifswald, Germany",
    url: "https://www.ipp.mpg.de/w7x",
    feedUrl: null,
    blurb: "Largest stellarator — proving the alternative path to steady-state fusion.",
  },
  {
    id: "ksc",
    name: "Kennedy Space Center",
    short: "KSC",
    kind: "space",
    lat: 28.5729, lon: -80.649,
    location: "Cape Canaveral, FL, USA",
    url: "https://www.nasa.gov/kennedy/",
    feedUrl: "https://www.nasa.gov/rss/dyn/breaking_news.rss",
    blurb: "NASA's primary launch complex — Apollo, Shuttle, Artemis.",
  },
  {
    id: "baikonur",
    name: "Baikonur Cosmodrome",
    short: "Baikonur",
    kind: "space",
    lat: 45.965, lon: 63.305,
    location: "Kazakhstan",
    url: "http://www.roscosmos.ru/",
    feedUrl: null,
    blurb: "Sputnik and Gagarin launched here; still flies every crewed Soyuz.",
  },
  {
    id: "guiana",
    name: "Guiana Space Centre",
    short: "CSG",
    kind: "space",
    lat: 5.236, lon: -52.768,
    location: "Kourou, French Guiana",
    url: "https://www.esa.int/Enabling_Support/Space_Transportation/Europe_s_Spaceport",
    feedUrl: "https://www.esa.int/rssfeed/Our_Activities/Space_Transportation",
    blurb: "Europe's equatorial spaceport — Ariane, Vega, and JWST's launch site.",
  },
  {
    id: "jpl",
    name: "NASA Jet Propulsion Laboratory",
    short: "JPL",
    kind: "space",
    lat: 34.2048, lon: -118.1711,
    location: "Pasadena, CA, USA",
    url: "https://www.jpl.nasa.gov/",
    feedUrl: null, // jpl.nasa.gov 403s feed readers
    blurb: "Builds and flies NASA's robotic fleet — Voyager to Europa Clipper.",
  },
  {
    id: "skao",
    name: "SKA Observatory (SA site)",
    short: "SKAO",
    kind: "radio",
    lat: -30.7211, lon: 21.4111,
    location: "Karoo, South Africa",
    url: "https://www.skao.int/",
    feedUrl: "https://www.skao.int/en/rss.xml",
    blurb: "Mid-frequency half of the Square Kilometre Array, under construction.",
  },
];

// Attach locally-downloaded cover images (scripts/fetch-facility-images.mjs).
for (const f of FACILITIES) {
  const img = IMAGE_MAP[f.id];
  if (img) f.image = img;
}

export const FACILITY_MAP = new Map(FACILITIES.map((f) => [f.id, f]));
